profiles/default
This unit for periodical trim is installed with the base group, so it only has to be activated. You can read up on it here: https://wiki.archlinux.org/index.php/Solid_state_drive#Periodic_TRIM
=> Add trim support

profiles/default
The liberation fonts will be used by Steam if they are installed. SteamOS uses these fonts as well.
The wqy-zenhei package allows Steam to display asian language characters.
=> Added fonts Steam uses

build.sh, profiles/default
This makes users able to connect to servers on their GamerOS machine with as gameros.local instead of the full IP address. This should work with any system with multicast DNS support. In my test it worked with Debian 10. I am not able to test with Windows 10 or MacOS here, but it should work with those. It did not work for me with Android or Windows 7.
=> Added mdns support

profiles/default
I was having issues with GamerOS booting slow on my Steam Machine.
Installing and enabling haveged, an entropy generator, sped up my boot
times by 2 minutes.
=> Added haveged for faster boot on low entropy systems

build.sh, profiles/default
This makes you able to select Alien FX in the menu if you have an Alienware Alpha or Steam Machine to change the color of the lights on the system.
I've created a package on the AUR which takes the script from the steamos-base-files. This is what is used here.
I did find a bug while working on this. The files in ``/etc/sudoers.d`` aren't loaded by sudo because ``build.sh`` adds a line below the include line in the sudoers file. With this pull request this is fixed by writing to the second to last line instead.
=> Support changing lights on Alienware Alpha

profiles/default
This change adds support for the Xbox One Wireless adapter by [medusalix](https://github.com/medusalix/xow).
It's tested on my box. The only problem is, after a restart you have to pair your controllers again. I'm not sure how to fix this, but the the xow project is very active at the moment, so maybe it's an upstream fix.
P.S. For me the re-pair problem only occurs, when the controllers are already connected during a reboot.
=> Added Xbox One Wireless adapter support

build.sh, profiles/default
Without password authentication enabled it is not possible to log in until the user adds a public key to the system. Steam-buddy can later be made to manage public keys for the gameros user.
=> Enabled ssh by default with only public key authentication

BUILDING.md, Dockerfile, build.sh
This PR adds support for building GamerOS images in Docker, which addresses some points in #63. 
To get this to work, I needed to make a few modifications to `build.sh` to support running `pikaur` as a normal user. By default, `pikaur` will run as it did before, so these changes shouldn't have any effect building outside Docker.
Also added are optional image output directory environment variables which the Docker image uses to move the image file outside the container.
=> Add docker support for building GamerOS images

rootfs/etc/polkit-1/rules.d/41-steamvr.rules, rootfs/usr/share/polkit-1/actions/org.gameros.steamvr.policy
When launching SteamVR, you will be prompted for sudo rights to run `setcaps` on `vrcompositor-launcher`, but GamerOS does not have a policykit agent running to display a password prompt:
```
if ! ${STEAM_ZENITY} --no-wrap --question --text="SteamVR requires superuser access to finish setup. Proceed?"; then
pErr 'Error: user declined superuser request.'
return 1
fi
pkexec setcap CAP_SYS_NICE=eip $STEAMVR_TOOLSDIR/bin/linux64/vrcompositor-launcher
```
This PR adds a policykit action and rule to allow sudoless access for `vrstartup.sh` to set this capability.
=> Add policykit action and rule to allow SteamVR to setcap on vrcompositor

manifest
This adds a patched version of the libretro-ppsspp package found in the Arch repo. The difference is that this package includes the assets and has been patched to use them. It is required for https://github.com/gamer-os/steam-buddy/pull/101
=> Add ppsspp for PSP support

build.sh, manifest
I was trying to make the following dongle work with GamerOS : 
And to succeed I had to do two operations : 
1. Force HCI mode to make the dongle an actual Bluetooth dongle, because it goes into HID mode by default. This can be achieved in two ways : 
- By pressing the "Connect" button while plugging it in
- By installing the `bluez-hid2hci` package from the [Arch repos](https://archlinux.org/packages/extra/x86_64/bluez-hid2hci/), in order to [automatically force it](https://wiki.archlinux.org/index.php/Bluetooth#Logitech_Bluetooth_USB_Dongle).
The second option is obviously way more convenient, so this pull request adds the package to the `manifest` file in a first commit.
2. Force the Bluetooth controller to automatically be powered on when plugged in : 
If the dongle is plugged in …
=> Better handling of Bluetooth dongles 

Dockerfile
This should be seen as temporary. It's not good. It breaks updating.
=> Fix pacman not working with a workaround

Dockerfile
I got it to build on Debian 10 like this. I totally forgot you need to use this version specificly.
=> Use the correct docker container

manifest
Steam beta now needs pipewire or won't start. If a user opts-in into Steam beta client, maybe they can't start the session.
=> Add `pipewire` and `lib32-pipewire`

rootfs/etc/systemd/journald.conf.d/00-journal-size.conf
On most computers with the current installation, logs made by [`journald` will chew up 4Gib](https://wiki.archlinux.org/title/Systemd/Journal#Journal_size_limit) that can be used for more interesting stuff.
=> Avoid journald chewing up 4G of disk space

build.sh
The garudalinux repo returns 404 and in [the official Chaotic-AUR homepage](https://aur.chaotic.cx) they list different steps to enable the repo and use it.
Here is the change to make it work again.
=> Fix Chaotic AUR repo

manifest
The project already builds `gamescope` as part of the distribution and
would be nice to have a way for advanced users to test the new XWayland
compositor as a ChimerOS session. It works for most games and would
eventually be the future for Steam machines (if that ever comes to light).
The package itself it's just scripts to make it work, is 18Kb insize
and should provide the same integrations and functionality as the current
steamos-session based on steamos-compositor-plus.
=> Add gamescope-session to the build

rootfs/etc/modprobe.d/system-tweaks.conf
This is needed for Wayland support, Prime support and some setups may benefit from it even if we don't support them.
=> Enable Kernel Modesetting for `nvidia`

build.sh, manifest
Use `PKGDEST` variable instead of cache for `extra_pkgs`. This should avoid messing with pikaur cache.
Increase SIZE to 10Gb so we don't fail the image creation. Image final size is 4.6Gb uncompressed and 1.4Gb compressed.
=> Avoid pikaur cache and increase Image builder size

manifest
This package will allow for Nvidia optimus-like machines to offload
render workloads with minimum configuration.
With nvidia version 465 onward this can be achieved by adding a minimal
xorg configuration file (not included in current install):
/etc/X11/xorg.conf.d/10-nvidia-prime.conf
````
Section "Device"
Identifier "iGPU"
Driver "modesetting"
EndSection
Section "Screen"
Identifier "iGPU"
Device "iGPU"
EndSection
Section "Device"
Identifier "dGPU"
Driver "nvidia"
BusID "PCI:<NVIDIA-PCI-ADDR>"
EndSection
````
Then test with:
$ DISPLAY :=0 prime-run glxinfo  | grep "OpenGL renderer"
$ DISPLAY :=0 prime-run vulkaninfo
=> Add nvidia-prime package

build.sh, manifest
This pull request fixes the DKMS modules building by : 
* Adding the `linux-headers` package required by the DKMS hook of the `*-dkms` packages, which fail silently otherwise
* Cleaning up all the source files in `/usr/src/` that will not be needed on the user's system
Successfully built and deployed in my fork that I made to rollback the NVIDIA driver to 470.82.00 using the `nvidia-470-xx-*` AUR packages (not in this PR).
=> Fix dkms build

manifest
This PR adds the [wavpack](https://archlinux.org/packages/extra/x86_64/wavpack/files/) package from the official Arch repositories, to fix the native version of [Worms W.M.D](https://store.steampowered.com/app/327030/Worms_WMD/), which is otherwise failing to launch due to `libwavpack.so` missing.
=> Add wavpack official Arch package (fix for Worms WMD)

manifest
This PR is a follow-up of #279 
I noticed after rebasing to ChimeraOS 28 that I forgot to add 2 packages for Worms W.M.D to work :
* [libcurl-gnutls](https://archlinux.org/packages/community/x86_64/libcurl-gnutls/)
* [libidn11](https://archlinux.org/packages/community/x86_64/libidn11/)
=> Add libcurl-gnutls and libidn11 (fix for Worms W.M.D)

rootfs/etc/udev/rules.d/01-asrock-LED-controller.rules
This PR creates a udev rule that ignores Asrock's motherboard rgb controller.
This is to prevent retroarch from using it as a gamepad input so me (and others) can play our retro games.
=> Create udev rule to ignore asrock led controller

rootfs/etc/modprobe.d/rz608.conf, rootfs/etc/udev/rules.d/99-rz608.rules
Added modprobe and udev rules for supporting the Aya Neo Pro WiFi module in the full OS. Solves #288.
=> MT7921K WiFi Support for Aya Neo Pro

rootfs/etc/systemd/logind.conf.d/power_off.conf
Adds a logind.conf.d folder with a config file that ignores power button pressing. Prerequisite for https://github.com/ChimeraOS/steamos-compositor-plus/pull/48 to be enabled.
=> Disable Systemd handling of XF86PowerOff events #299 

rootfs/usr/lib/systemd/system-shutdown/mt7921e.shutdown
Unload mt7921e driver on shutdown to prevent bug found here https://discordapp.com/channels/560281725175988233/560281725175988238/951312146963247155
=> Fix kernel panic on Aya Neo 2021

.github/workflows/main.yml
Only trigger the image generation if a push to master. Since every other branch should not create a release and ideally would be tested locally.
=> Only trigger build on commit to master

manifest
Found a more thorough workaround for the phantom controller input. Enables service from [here](https://github.com/ShadowBlip/aya-neo-fixes/blob/main/phantom-input.service).
=> Phantom Input Remover

manifest
The AUR package has been split into Wayland and X11 (XWayland) version. The `-x11` variant includes mangoapp binaries.
=> Use mangohud-x11 from AUR

manifest
This allows for easier development and testing on the device itself.
=> Don't delete include

manifest, rootfs/etc/systemd/system/bluetooth-workaround.service
Bluetooth wont start if it doesnt have `/var/lib/bluetooth` directory in
place. Since we overlay `/var` we cant deploy the directory Archlinux
worked around in their package so we add a tiny service that will just
create that directory.
=> Add bluetooth-workaround service file

build.sh
Time to build reduced to an exact hour and image went to 1.87Gb to 1.75Gb on a full gnome build.
=> Add multithread and higher compression

.github/workflows/main.yml, BUILDING.md, Dockerfile
Image wont build if no volume is mounted for `/workdir` thus making less likely to use wrong build files.
=> Make workdir a mandatory docker volume

build.sh
This will avoid the image failing on the last step from "resource busy". Should be safe since we are not using any binds directly.
=> Do lazy unmounts

build.sh, rootfs/etc/lightdm/lightdm.conf, rootfs/etc/lightdm/lightdm.conf.d/10-chimeraos-session.conf, rootfs/usr/bin/chimera-session, rootfs/usr/bin/chimera-session-use-gamescope, rootfs/usr/bin/chimera-session-use-lightdm
Split LightDM configuration files into a basic configuration for all sessions, a user autologin name and a session declaration. Rework chimeraos-session-switcher to use 10-chimeraos-session.conf to change sessions. Tested on my branch and works.
Further work would need to add steamos-session-switcher to be able to work on Steam client (at leas on gamepadui) and remove some leftovers.
=> Session switcher rework to use LightDM for all sessions

manifest
Just updated :) https://archlinux.org/packages/community/x86_64/libretro-mame/
=> Switch libretro-mame to ArchLinux repos

rootfs/etc/udev/hwdb.d/61-sensor-local.hwdb
This will add the mount matrix of the OXP Mini AMD (and maybe others) for the accelerometer to work correctly.
The change is already merged upstream in https://github.com/systemd/systemd/pull/24158 but would be necessary until v252 of systemd hits Arch repos.
=> Add mount matrix for OXP accelerometer

rootfs/usr/bin/steamos-polkit-helpers/steamos-set-hostname, rootfs/usr/bin/steamos-polkit-helpers/steamos-set-timezone, rootfs/usr/share/polkit-1/actions/org.chimeraos.host.policy
These scripts are called by Steam Client to allow setting of timezone and hostname system wide.
=> Fix setting hostname and timezone via client

manifest
Pipewire is stable enough now to be used. Being using it for a long time on all my setups without issues.
=> Replace pulseaudio with pipewire stack

build.sh, manifest
We dont build the kernel package because it will take too much time. Any
package we could put in that variable should be accessible via pacman
repos. Pacman configuration should be edited accordingly if non-standard
kernel is desired.
=> Introduce KERNEL_PACKAGE variable to swap kernels

manifest
We don't use it. If the image needs it, we should add it later.
=> Remove bcache-tools

Dockerfile
Quick fix for build errors on python AUR packages that don't yet depend on `python-setuptools`
=> Fixup: Add python-tools to fix python-smbus2

manifest
Current linux package version 5.19+ bootloops on syslinux bootloader with UEFI systems. Prevent that for now until we find a better solution.
Possible solutions would be:
- Wait for a fix in either syslinux or linux-mainline (current 6.0-rc1 also have the issue)
- Change bootloader to something else (systemd-boot could be an option if we drop BIOS support or fall back to GRUB)
=> Use linux-lts to prevent bootloops on UEFI

manifest
Since we introduced KERNEL_PACKAGE variable this one is needed.
=> Use broadcom-wl-dkms

manifest
User can install it via `pip` if needed.
=> Remove podman-compose

manifest
This will slim the image a couple megabytes. If the suer needs to unlock and use the image for developing stuff it should install `base-devel` anyway.
=> Remove make, gcc and deps without deleting headers

manifest
Allows for a slimmer image. Removes pacman hooks before deleting packages so dkms remove is not triggered.
=> Allow removing dkms and kernel headers

manifest
Mesa is phasing out Intel driver in favor of modesetting since v20.0. We should remove it. Using modesetting is compatible with Nvidia prime configurations and iris graphics hardware.
=> Remove xf86-video-intel Xorg driver

Dockerfile
Since rsync is not installed within the docker-container reflector will spit errors at you. This forces reflector to use http or https.
=> Dockerfile: only use http or https

build.sh
On github and locally the python-leveldb package failed to build for me. Setting this worked around the issue for me.
=> Workaround: fatal: transport 'file' not allowed

rootfs/etc/udev/hwdb.d/61-sensor-local.hwdb
The configuration is already in current systemd v252.1
=> Remove OneXPlayer mini AMD sensor config

.github/workflows/main.yml, build.sh
Reference: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Update deprecated set-output command

build.sh, manifest
Building all packages from AUR directly doesn´t affect the build time significantly.
=> Remove chaotic-aur repository

rootfs/etc/udev/rules.d/00-ntfs3-default-mount.rules
This workarounds `mount` command without a explicit type declaration. Maybe the best solution comes in modifying the script to detect NTFS and mount it with explicit type, but this works it around and doesn't seem have any downsides so far.
Reference: https://wiki.archlinux.org/title/NTFS#unknown_filesystem_type_'ntfs'
=> Add udev rule for ntfs3 driver

manifest
The service can be enabled by the user but even then it won't start if there is no configuration file.
=> Add hhfc package

build.sh
Freeze the repositories to the build date so when unlocking the image packages like the kernel won't break.
=> Freeze archive by date

.gitignore, build.sh, manifest, pkgs/chimeraos-device-quirks-git/PKGBUILD
This will make any PKGBUILD inside `pkgs` directory to be built as a package and installed in the image like all other AUR packages. This can be usefu for distro-specific packages or versions of them that need to be patched.
For now the packages are kept in our repository but eventually we can add git submodules to keep them in their own repos and even freeze them to a specific version/build (for more reproducible-ish builds).
=> Build our own PKGBUILDs

build.sh
steam-removable-media now supports formatting mmcblk0 using GamepadUI. Gives the user permission to run the script. The button is only active if an mmcblk device is detected by steam and can only format mmcblk0. The new script simply runs the old script with a hardcoded mmcblk0 parameter.
=> Switch to using polkit for managing media in chimera app

build.sh, manifest, pkgs/lib32-mesa-22.3.1-anv-patch/0001-anv-force-MEDIA_INTERFACE_DESCRIPTOR_LOAD-reemit-aft.patch, pkgs/lib32-mesa-22.3.1-anv-patch/0001-anv-gamescope.patch, pkgs/lib32-mesa-22.3.1-anv-patch/0003-d3d12-Don-t-crash-when-libd3d12.so-can-t-be-found.patch, pkgs/lib32-mesa-22.3.1-anv-patch/LICENSE, pkgs/lib32-mesa-22.3.1-anv-patch/PKGBUILD, pkgs/mesa-22.3.1-anv-patch/0001-anv-force-MEDIA_INTERFACE_DESCRIPTOR_LOAD-reemit-aft.patch, pkgs/mesa-22.3.1-anv-patch/0001-anv-gamescope.patch, pkgs/mesa-22.3.1-anv-patch/LICENSE, pkgs/mesa-22.3.1-anv-patch/PKGBUILD
We're using the Arch Linux's PKGBUILD including the additional ANV patch to fix the issues where gamescope would fail on Intel devices.
The patches only effect Intel specific files called `ISL_FORMAT` and `ANV_FORMATS`
=> Patch Mesa 22.3.1 to fix gamescope issues for Intel

manifest
Adds ryzenadj-controller-git and enables user service that depends on it from device-quirks.
=> Add ryzenadj-controller

manifest, pkgs/r8168-dkms/PKGBUILD, pkgs/r8168-dkms/dkms.conf, pkgs/r8168-dkms/r8168-dkms.install
Causes regressions with r8169 driver. The package blacklists r8169 kernel module and can't be reenabled automatically. Maybe if there are enough users with this chip, we should redo the packaging without the blacklisting part.
=> Remove r8168 driver

manifest
Moved to community package
https://archlinux.org/packages/community/any/python-pyinotify/
=> add python-inotify-simple to packages, not in AUR anymore

manifest
From PKGBUILD:
```
```
Some are already there by dependencies in other places. But this makes them explicit.
=> Jupiter deps

manifest
dependencies for adding Atari 7800 and SuperGameBoy support (draft pull request 260 https://github.com/ChimeraOS/chimera/pull/260 )
=> Add Citra, Mesen-S, and ProSystem libretro core packages

pkgs/50-mangohud/PKGBUILD, pkgs/50-mangohud/resolution.patch
Confirmed to fix issues on devices that don't rely on specifying a `-w` `-h` nested value to work such as the intel One Xplayer 1S.
- Fixes the position of the performance overlay on the Aokzoe and Aya Neo Air
=> Fix position issues with mangoapp

rootfs/usr/bin/steamos-polkit-helpers/steamos-priv-write
Previous version always "fails" to success. It has caused issues on users with AMD cards getting set to 15w by steam.
=> fix commitwrite/declinewrite

manifest, pkgs/50-mangohud/PKGBUILD, pkgs/50-mangohud/resolution.patch
See also https://github.com/flightlessmango/MangoHud/commit/bc282cf300ed5b6831177cf3e6753bc20f48e942
I have updated the PKGBUILD according to master, and updated the commit. It should now build without pinning the package. 
I also had to reformat the resolution.patch a bit.
=> Mangohud update

pkgs/50-pipewire/PKGBUILD, pkgs/50-pipewire/pipewire-pulse.install, pkgs/50-pipewire/pipewire.install
0.3.68 breaks the `-steamos3` parameter and it's undetermined whether it's Valve or the upstream project's "bug" to fix. We may need to start reverting or patching pipewire in the feature depending on what happens.
Related tickets:
- https://github.com/ValveSoftware/steam-for-linux/issues/9337
- https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3145
=> Manually use 0.3.67 pipewire for now

.github/workflows/builder.yml, .github/workflows/main.yml, build.sh
1. Add an extra workflow that creates a new builder image daily (regardless of pkgbuild changes). This way we can follow arch-linux package updates. (AUR will always be built). This will run 2 am daily, or via manual trigger to fill a cache.
2. Implement caching based on PKGBUILD hash, if no changes are found the build will continue using the image built before. Skipping the endless mesa rebuild.
3. Implement PR checks to master, so building an image without releasing it.
4. Fix package overrides (added an if statement here).
=> Add caching to build system

manifest
The immediate benefit to this is for remote frzr deployments but this has many other use cases as well I'd like to build on.
=> Add sshfs for remote mounting support

.gitignore, build-image.sh, utils/build-full-image-local.sh, utils/build-packages-locally.sh
This edits some scripts so it can skip tarring on local builds.
Also adds keeping the .cache folder so AUR builds will go a lot faster since it does not need to fetch sources all the time ;)
=> local builds

.github/workflows/main.yml
I found out that sometimes branches would not create a new docker container. This add a additional check if a container with the tag already exists, otherwise create one.
=> Workflow fixes

manifest, pkgs/00-mesa-anv-gamescope/PKGBUILD, pkgs/01-lib32-mesa-anv-gamescope/PKGBUILD
I came across the fact that [valve also uses a seperate radv driver](https://gitlab.com/evlaV/jupiter-PKGBUILD/-/blob/master/mesa-radv/PKGBUILD)
I thought why could we not do the same with our patched intel driver? So I tried this. No idea if it works, so looking for testers :)
=> only build intel vulkan driver

manifest
Adds ayaled package by Maya Matuszczyk for controlling the ring LED's on the AIR, AIR Pro, 2, and GEEK AYANEO models. Usage instructions are available on the git repo. It provides a web server to change the LED settings over GET requests. This will need to be manually enabled by the user. It comes with some sane defaults but can be customized as the user wants.
https://github.com/Maccraft123/ayaled
=> Add ayaled AUR package

manifest
Was added as a workaround for pyglet not working with animated splash on chimera. Won't be needed when https://github.com/ChimeraOS/chimera/commit/984a33a2a44052f5144f666de80add8518c7ed23 gets released.
=> Remove python-gobject

manifest
Cryouilities makes use of wget during the install process.
=> Add wget for cryoutilities compatibility

build-image.sh
I noticed that most build failures recently are the final build step not finding certain packages. This PR adds the builder mirrorlist to the chroot as well, and installing the official package when done. Reasoning is that maybe the mirrors used in the build are not as up-to-date as the freshly created docker image.
=> use builder mirrorlist

build-image.sh
It will be overwritten anyway with archive date later on.
https://github.com/ChimeraOS/chimeraos/blob/master/build-image.sh#L220
=> Remove unneeded mirrorlist update

rootfs/usr/bin/chimera-session
This fixes switching to the gamepadui-with-qam session caused by renaming of the service and session.
=> Fix only-qam session switching

manifest
I noticed that in the current version of Chimera OS is no method present to update device firmware. Therefore I added "gnome-firmware" to the manifest of ChimeraOS. This tool should allow every user from the desktop session to easily and safely update their device firmware. If you do not wan't to include a GUI tool please at least include the underlying "fwupd" tool instad of "gnome-firmware".
=> Add tools to update device firmware

.gitmodules, manifest
python-asyncio recently removed coroutine from the library. This breaks the message handling in ryzenadj-controller. Remove ryzenadj-controller for now until I can be bothered to fix it.
=> Remove ryzenadj-controller and don't enable ryzen-tctl

rootfs/usr/share/wireplumber/main.lua.d/50-alsa-config.lua
This seems to be beneficial on all devices I've messed with. This won't fix all hardware unfortunately, but it should be a much better default for most hardware configurations when gamescope is being used.
=> Add default config for wireplumber

manifest
This PR adds only 0.26 MiB of size. It allows the Nautilus file manager to generate video thumbnails. You could imagine this being nice especially for Discord users, for instance.
Before:
After:
Size:
=> Enable video thumbnail previews in file manager

manifest
The `pipewire` module needs to be loaded by the user, elsewise it will break the screen recording entirely on the desktop. Fixes #772
=> Fix screen recording on Wayland

manifest
This package massively improves the terminal. It allows for pressing tab to autofill commands, subcommands, and files, just like a normal distro.
Adds ~0.83 MiB
Closes #777
=> Improve terminal with bash-completion for standard autofill

manifest
ChimeraOS currently ships Eye of GNOME (eog) as it's default image viewer. Eye of GNOME is unmaintained, deprecated, and has officially been replaced with the modern GTK4 image viewer called Loupe. This newer application is more stable, has better features, looks nicer, and is based on the modern LibAdwaita UI. It would be better for ChimeraOS, too, as it has far superior touch features, making it the ideal image viewer for touchscreen devices such as handhelds.
There are also security and performance improvements compared to Eye of GNOME, as well as more accurate SVG rendering and more supported formats.
=> Replace legacy image viewer with official modern GNOME image viewer

manifest
This PR removes File roller as it is obscolete due to Nautilus natively having both compression and decompression features. Adds duplicate functionality. This cleans up the install a bit.
Also added `p7zip` and `unrar` packages. These serve to allow Nautilus to natively compress and decompress `.7z` and `.rar` files natively.
Frees >=4.11 MiB
=> Remove File Roller as it duplicates built-in Nautilus functionality (obscolete package)

manifest
It is essential for desktop users to have the power to manage processes. GNOME System Monitor is easily the best at this, and is a core GNOME app. This PR adds it to improve the general desktop experience.
Adds 14.02 MiB
Closes #765
=> Add GNOME System Monitor for easy user process management

manifest
The gamemode daemon does not appear to be helping us as much as we may like and adding the cpupower tool can give us more fine controls over how the system manages the power budgets.
=> Add cpupower and remove gamemode daemon

aur-pkgs/build-aur-package.sh
To prevent failed build task continuing, introduce exit code check.
Example:
<https://github.com/ChimeraOS/chimeraos/actions/runs/7939157980/job/21682894843>
This job failed to package but the whole task still continued.
=> Add AUR Package Build Exit Code Check

manifest
Adds evdev-keepalive udev service. This works around an issue with some AYANEO devices and other 8BitDo controllers which will either sleep randomly or continuously restart themselves when they aren't grabbed by a process. This causes some devices to repeatedly vibrate during boot or never fully intialize the xpad driver.
=> Add evdev-keepalive

manifest
Cosmetic changes, only for ease of use on my end. I recently installed Lazyvim on my development machine. It has auto-formatters for bash that conflict with the manifest. This change allows me to use vim instead of nano when editing the manifest.
=> Format manifest

manifest
Removes BMI260 DKMS module in favor of using a kernel patch directly.
=> Remove bmi260 DKMS

rootfs/etc/mkinitcpio.conf
The compression algorithm did not make any difference in my tests regarding boot times, but it decreases the size of a file meant to be copied at least one, and potentially two, times to the 512MiB vfat partition.
Having current initramfs taking up too much space clashes with the "easy kernel swaping" feature to be implemented.
=> mkinitcpio: compress the image with xz

rootfs/etc/mkinitcpio.conf
Archlinux switched to including microcode in the initramfs as the preferred method to load amd-ucode.img and intel-ucode.img and also deprecated using initrd options on the bootloader.
=> mkinitcpio: add microcode hook

build-image.sh
Enable btrfs compression at build-time as well as run-time.
The image boots and game just fine and I haven't seen any noticeable slowdown or system load in any of my device.
Chosen compression levels are to achieve minimal image size when building in github and installing to the end-user system and fast write speed for the user (since subvolumes are mounted with a much less aggressive compression ratio).
=> Btrfs compression

build-image.sh, rootfs/etc/mkinitcpio.conf, rootfs/etc/vconsole.conf
Use systemd on initrd instead of busybox to solve two bugs:
- when two chimeraos are installed booting a device might result in mounting the rootfs of the other device
- Issue #919 https://github.com/ChimeraOS/chimeraos/issues/919
/efi will be automounted by systemd: remove the fstab entry.
If the default subvolume of / is changed boot will fail: fix this by mentioning subvolumes by theirs ID (fixed since installation).
This superceedes https://github.com/ChimeraOS/chimeraos/pull/901 and https://github.com/ChimeraOS/chimeraos/pull/914
=> mkinitcpio: use systemd and adapt /etc/fstab

build-image.sh, manifest
Razer is well-known into desktop PC gaming and also makes some latops. Add the required dkms kernel module and daemon to allow configuring those devices. Multiple frontends are available for the user to choose from and none is included.
=> razer: allow control of such hardware

manifest
Replaces the functionality of the steam suspend feature that HandyGCCS provided in an input manager agnostic way.
=> Add steam-powerbuttond-git

manifest
The package adds support for 32 bit SDL and is needed by some older native games, like "Portal Stories: Mel".
It adds slightly over 2 MB in size.
=> Add lib32-sdl2 for native 32 bit Linux games

manifest
Allows certain tweaks like minimize/maximize buttons on windows without having to use gsettings manually.
=> Add Gnome Tweaks app to the manifest.

rootfs/usr/bin/mkswapfile
Since btrfs compression of system image enabled by default, swapfile has been broken.
Here is log:
```
$ systemctl status home-swapfile.swap
× home-swapfile.swap - Swap
Loaded: loaded (/etc/systemd/system/home-swapfile.swap; enabled; preset: disabled)
Active: failed (Result: exit-code) since Tue 2024-04-30 20:57:21 CST; 2h 20min ago
What: /home/swapfile
CPU: 8ms
Apr 30 20:57:21 chimeros systemd[1]: Activating swap Swap...
Apr 30 20:57:21 chimeros swapon[486]: swapon: /home/swapfile: swapon failed: Invalid argument
Apr 30 20:57:21 chimeros systemd[1]: home-swapfile.swap: Swap process exited, code=exited, status=255/EXCEPTION
```
This pull request means to solve this problem.
=> fix: Disable btrfs compression to make swapon work

Dockerfile
This change uses the [archlinux-aur](https://github.com/greyltc-org/docker-archlinux-aur) image as the base for building in Docker. It allows us to install packages from the AUR in the container that may be required to build other AUR packages (like OpenGamepadUI)
=> Use archlinux-aur as Docker base image and install InputPlumber as a dependency to build OpenGamepadUI

build-image.sh, manifest
As per title: use iptables-nft instead of the deprecated iptables.
See https://gitlab.archlinux.org/archlinux/packaging/packages/iptables/-/issues/1 for more details.
The deprecated iptables is not completely suitable for docker or podman as stated in that page.
The reason this is not in PACKAGES is the following error will appear:
```
error: unresolvable package conflicts detected
:: iptables-nft-1:1.8.10-1 and iptables-1:1.8.10-1 are in conflict. Remove iptables? [y/N] 
:: iptables-nft-1:1.8.10-1 and iptables-1:1.8.10-1 are in conflict
error: failed to prepare transaction (conflicting dependencies)
```
=> Use nftables instead of the deprecated iptables

rootfs/etc/sudoers.d/systemctl_needed, rootfs/usr/bin/chimera-session, rootfs/usr/lib/os-session-select
- Ensures input intercept is always set to NONE instead of PASS or ALL
- Ensures a game-specific button layout isn't loaded when is desktop mode
Steam-plus and opengamepadui sessions will set the intercept mode they need when they start.
=> fix(InputPlumber): Restart InputPlumber when swithcing to desktop

manifest
The explicit sync support has hit stable with the Nvidia drivers and it is now possible for us to begin to support Nvidia again.
=> Attempt to add Nvidia support back

rootfs/usr/lib/frzr.d/install-0003-root_part_gpt.migration
The installation was failing from devices like /dev/sda but was working on /dev/nvme and /dev/mmcblk disks due to a wrong regex used to extract the disk from the partition.
=> Fix installation in non-nvme and non-mmcblk device types

build-image.sh, rootfs/usr/lib/frzr.d/unlock-0002-pacman-db.unlock
To avoid database inconsistencies and retain the correct behavior of having pacman reporting the missing database move the whole pacman directory as before changes to adapt to the refactored frzr.
=> Move the whole pacman directory

manifest, rootfs/etc/udev/rules.d/00-ntfs3-default-mount.rules, rootfs/etc/udev/rules.d/81-wol.rules
This PR moves udev rules and additional dependencies for those udev rules into device-quirks package. 
Also accomplish what is requested here: https://github.com/ChimeraOS/device-quirks/pull/114
=> Move udev rules

build-image.sh
Check and debug both increase the build time for package, while debug also increase size for no benefit as chimera does not ship with a debugger and people don't use one on system software anyway: remove both options.
=> Disable check and debug for makepkg on the final image

manifest
Add wireless-regdb package: this package brings a file in /etc that is fully commented and by default nothing changes from a default configuration.
When a user changes the file /etc/conf.d/wireless-regdom decommenting the regulatory domain more wifi frequencies can be used thus augmenting wifi speed and possible networks to connect to.
=> Add wireless-regdb to packages
