ChimeraOS/chimeraos

install.sh

Quick fix to some mistakes [as missing mesa driver, Added option to detect modern AMD Graphics cards like Vega, Polaris, Raven Ridge (Ryzen APUs)]

Fixed GPU support

---

BUILDING.md
build.sh

This should be everything you have to know. Let me know if you find any typos

Added build instructions

---

BUILDING.md

Fixed confusing instruction

---

build.sh

This fixes visudo not being usable and it helps with my sanity. I'm way to used to typing vi.

Make vi command start vim

---

build.sh

This way is a bit safer. I just create a new configuration file in ``/etc/sudoers.d/``.

Fixed sudo issues

---

build.sh

This is all it had in it anyway. I've added gamer to it. I have tested this exact configuration, but I have not rebuild the image, upgraded and tested again yet.

Fix sudoers file

---

build.sh

This sets vim as default editor

Fix visudo

---

profiles/default

This goes hand in hand with:
https://github.com/gamer-os/steam-buddy/pull/62

add dolphin to retroarch cores

---

manifest

Add rtl88x2bu kernel driver

---

manifest

Added package `r8152-dkms` from AUR to support ethernet chipsets

Add support for Realtek RTL8152/RTL8153/RTL8154/RTL8156

---

build.sh
manifest

First contribution in a long while.

Add os-release in rootfs

---

manifest

The version in the repositories is 3.11.22 while the latest is 3.11.28-beta4 released with the Deck.

Use gamescope-git

---

manifest

Add nintendo-udev package

---

build.sh

requirement for https://github.com/ChimeraOS/chimera/pull/230

format-media.sh sudoers

---

Dockerfile
build.sh

Improves both download times and build times for AUR packages.

Allow multicore and multiple download

---

manifest

Package seems abandoned and fails to build

Remove srt-live-server package due build failure

---

manifest

This adds `--force-orientation ` for use on handhelds or any other device that needs screen rotation.

Use gamescope-plus

---

manifest

Remove opencl-nvidia libraries

---

manifest

Can be installed by suer if they like

Remove libretro-shaders

---

manifest

since v 5.19.6 the fix for bootloops on syslinux booting UEFI is fixed

Build with fixed Linux package

---

manifest

Little driver for fan control.

Add oxp-platform driver

---

build.sh
rootfs/usr/bin/jupiter-biosupdate
rootfs/usr/bin/steamos-update

They are part of this commit in gamesope-session (https://github.com/ChimeraOS/gamescope-session/commit/3f435946e622ceb333436b47554f9db27ce6ad76) and then tested and fixed in latest master

Remove update scripts part of gamescope-session

---

manifest

Replace gnome-terminal with gnome-console

---

Dockerfile

Pikaur update in AUR has new dependencies.
See https://aur.archlinux.org/cgit/aur.git/commit/?h=pikaur&id=cf636f7b968773b2c4f41f4a624dccc10520e75f

Update Dockerfile dependencies

---

build.sh
manifest
rootfs/etc/pacman.conf

Don't leak pacman configuration into the image.

Isolate builder

---

rootfs/usr/lib/frzr.d/bootconfig.conf

This depends on https://github.com/ChimeraOS/frzr/pull/26 to be effective. Otherwise can be merged but will have no effect.

Use frzr custom boot arguments

---

manifest

No new packages, just sort everything alphabetically. Makes it easier to review manifest. Y Z precedes a b.

Sort manifest

---

rootfs/usr/lib/frzr.d/bootconfig.conf

Improves compatibility with ryzenadj for 6800u devices.

Add iomem=relaxed

---

rootfs/usr/bin/frzr-postupdate-script
rootfs/usr/lib/frzr.d/require_reboot.migration

This needs to be merged to keep the same functionality when https://github.com/ChimeraOS/frzr/pull/32 gets released/included.

Frzr migrations

---

pkgs/00-mesa-anv-gamescope/0001-anv-force-MEDIA_INTERFACE_DESCRIPTOR_LOAD-reemit-aft.patch
pkgs/00-mesa-anv-gamescope/0002-iris-Retry-DRM_IOCTL_I915_GEM_EXECBUFFER2-on-ENOMEM.patch
pkgs/00-mesa-anv-gamescope/0003-Revert-iris-Avoid-abort-if-kernel-can-t-allocate-mem.patch
pkgs/00-mesa-anv-gamescope/0004-anv-gamescope.patch
pkgs/00-mesa-anv-gamescope/PKGBUILD
pkgs/01-lib32-mesa-anv-gamescope/0001-anv-force-MEDIA_INTERFACE_DESCRIPTOR_LOAD-reemit-aft.patch
pkgs/01-lib32-mesa-anv-gamescope/0002-iris-Retry-DRM_IOCTL_I915_GEM_EXECBUFFER2-on-ENOMEM.patch
pkgs/01-lib32-mesa-anv-gamescope/0003-Revert-iris-Avoid-abort-if-kernel-can-t-allocate-mem.patch
pkgs/01-lib32-mesa-anv-gamescope/0003-d3d12-Don-t-crash-when-libd3d12.so-can-t-be-found.patch
pkgs/01-lib32-mesa-anv-gamescope/0004-anv-gamescope.patch
pkgs/01-lib32-mesa-anv-gamescope/PKGBUILD

Mesa 22.3.5 and newer has serious issues for AMD with 4K panels.

Downgrade Mesa to 22.3.4

---

manifest

Maybe first good to test this. But assuming it works this should fix some intel mangohud issues after further investigation.
See also
https://github.com/flightlessmango/MangoHud/issues/850#issuecomment-1298362427
Supersedes #564

Add intel_gpu_top and set permissions

---

build.sh

After my weekend I'll create a fix properly. But this should fix when no overrides are used for now.

Quick fix for build failure

---

manifest

pre-req for future DOS support

add dosbox-pure core

---

manifest

add zip mount capability for future functions

Add fuse-zip to mount zip files

---

.github/workflows/main.yml

I made an oopsie here.
Sorry xpadneo-dkms

Fix so last AUR package does get included

---

pkgs/50-mangohud/PKGBUILD

Fixes some things:
https://github.com/flightlessmango/MangoHud/releases/tag/v0.6.9-1

Update Mangohud to 0.6.9-1 hotfix

---

build-image.sh
manifest

Use our own kernel package from [ChimeraOS/linux-chimeraos](https://github.com/ChimeraOS/linux-chimeraos)

Add chimeraos kernel

---

manifest

Causes negative experience for handheld users and has no benefits

Remove iio-sensor-proxy. 

---

manifest

Forward port fixes in stable-43 branch to master

Forward port fixes

---

manifest

Should also be added to install-media
Closes #597

Add `modemmanager` package to allow GSM modules

---

.gitignore
Dockerfile
build-image.sh

This follows up https://github.com/ChimeraOS/chimeraos/pull/675 I squashed all relevant changes into one commit and made sure nothing unrelated got added.

sed check -> !check and replace result in chroot

---

Dockerfile
aur-pkgs/build-aur-package.sh

The chimera pkg builds successfully with these changes

Pull Dave Reisner's key and use pacman's keyring

---

manifest

Included AUR package for Noto Fonts Emoji

Fix Emoji Dispaly Error

---

manifest

Is already upstreamed even on stable package

Remove asus-cirrus-firmware-git package

---

manifest

Add efibootmgr to support dual booting with Windows

Add efibootmgr to support dual booting with Windows

---

rootfs/usr/bin/chimera-session-use-lightdm
rootfs/usr/lib/os-session-select

- use setsid to push lightdm restarts to tty6
auto-format did some stuff as well

Use different tty to restart lightdm.

---

manifest

Added gvfs-nfs so that Nautilus can mount via GUI

---

rootfs/usr/lib/frzr.d/bootconfig.conf

We need to use nvidia drm modesetting for gamescope

Add Nvidia DRM modesetting bootloader option
